spring:
  port: ${SERVER_PORT:8080}
  application:
    name: loan-manager
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:15433}/${DB_NAME:loan-manager}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  issuer: loanAPI
  type: Bearer

aws:
  s3:
    bucket: loan-manager-bucket-2026
